group:
  # Active Plugin Repositories
  - files:
      # Base Files
      - source: templates/.nvmrc
        dest: .nvmrc
      - source: templates/.editorconfig
        dest: .editorconfig
      - source: templates/license.txt
        dest: license.txt
      - source: templates/.eslintignore
        dest: .eslintignore
      - source: templates/.stylelintrc
        dest: .stylelintrc
      - source: templates/babel.config.json
        dest: babel.config.json
      - source: templates/gulpfile.js
        dest: gulpfile.js
      - source: templates/.gitattributes
        dest: .gitattributes

      # GitHub Folder
      - source: templates/pull_request_template.md
        dest: .github/pull_request_template.md

      # Changelog Folder
      - source: templates/changelog/.gitkeep
        dest: changelog/.gitkeep

      # Binary Folder
      - source: templates/bin/check-changelog.sh
        dest: bin/check-changelog.sh
      - source: templates/bin/class-tec-changelog-formatter.php
        dest: bin/class-tec-changelog-formatter.php
      - source: templates/bin/process-changelog.sh
        dest: bin/process-changelog.sh
      - source: templates/bin/ModifiedSemverVersioning.php
        dest: bin/ModifiedSemverVersioning.php

      # GitHub Workflows
      - source: templates/workflows/lint.yml
        dest: .github/workflows/lint.yml
      - source: templates/workflows/release-branch.yml
        dest: .github/workflows/release-branch.yml
      - source: templates/workflows/link-project.yml
        dest: .github/workflows/link-project.yml
      - source: templates/workflows/phpcs.yml
        dest: .github/workflows/phpcs.yml
      - source: templates/workflows/changelogger.yml
        dest: .github/workflows/changelogger.yml
    repos: |
      the-events-calendar/tribe-common@master
      the-events-calendar/the-events-calendar@master
      the-events-calendar/events-pro@master
      the-events-calendar/events-eventbrite@master
      the-events-calendar/events-community@master
      the-events-calendar/events-filterbar@master
      the-events-calendar/event-tickets@master
      the-events-calendar/event-tickets-plus@master

  # Promoter
  - files:
      - source: templates/pull_request_template.md
        dest: .github/pull_request_template.md
      - source: templates/workflows/link-project.yml
        dest: .github/workflows/link-project.yml
    repos: |
      the-events-calendar/promoter@server/production

  # Inactive Plugin Repositories
  - files:
      # Base Files
      - source: templates/.nvmrc
        dest: .nvmrc
      - source: templates/.editorconfig
        dest: .editorconfig
      - source: templates/license.txt
        dest: license.txt
      - source: templates/.eslintignore
        dest: .eslintignore
      - source: templates/.stylelintrc
        dest: .stylelintrc
      - source: templates/babel.config.json
        dest: babel.config.json
      - source: templates/gulpfile.js
        dest: gulpfile.js
      - source: templates/.gitattributes
        dest: .gitattributes

      # GitHub Folder
      - source: templates/pull_request_template.md
        dest: .github/pull_request_template.md

      # GitHub Workflows
      - source: templates/workflows/lint.yml
        dest: .github/workflows/lint.yml
      - source: templates/workflows/link-project.yml
        dest: .github/workflows/link-project.yml
      - source: templates/workflows/phpcs.yml
        dest: .github/workflows/phpcs.yml
    repos: |
      the-events-calendar/events-automator@main
      the-events-calendar/events-virtual@master
      the-events-calendar/events-community-tickets@master
      the-events-calendar/event-tickets-wallet-plus@main
