group:
  # Active Plugin Repositories
  - files:
      # Base Files
      - source: templates/.browserslistrc
        dest: .browserslistrc
      - source: templates/.nvmrc
        dest: .nvmrc
      - source: templates/.editorconfig
        dest: .editorconfig
      - source: templates/license.txt
        dest: license.txt
      - source: templates/.eslintignore
        dest: .eslintignore
      - source: templates/.stylelintrc.json
        dest: .stylelintrc.json
      - source: templates/.gitattributes
        dest: .gitattributes

      # GitHub Folder
      - source: templates/pull_request_template.md
        dest: .github/pull_request_template.md

      # Changelog Folder
      - source: templates/changelog/.gitkeep
        dest: changelog/.gitkeep

      # Binary Folder
      - source: templates/bin/check-changelog.sh
        dest: bin/check-changelog.sh
      - source: templates/bin/class-tec-changelog-formatter.php
        dest: bin/class-tec-changelog-formatter.php
      - source: templates/bin/process-changelog.sh
        dest: bin/process-changelog.sh
      - source: templates/bin/ModifiedSemverVersioning.php
        dest: bin/ModifiedSemverVersioning.php
      - source: templates/bin/trim-readme-changelog.sh
        dest: bin/trim-readme-changelog.sh

      # GitHub Workflows
      - source: templates/workflows/release-process-changelog.yml
        dest: .github/workflows/release-process-changelog.yml
      - source: templates/workflows/release-prepare-branch.yml
        dest: .github/workflows/release-prepare-branch.yml
      - source: templates/workflows/release-sync-translations.yml
        dest: .github/workflows/release-sync-translations.yml
      - source: templates/workflows/release-merge-forward.yml
        dest: .github/workflows/release-merge-forward.yml
      - source: templates/workflows/release-replace-tbd-entries.yml
        dest: .github/workflows/release-replace-tbd-entries.yml
      - source: templates/workflows/lint.yml
        dest: .github/workflows/lint.yml
      - source: templates/workflows/link-project.yml
        dest: .github/workflows/link-project.yml
      - source: templates/workflows/phpcs.yml
        dest: .github/workflows/phpcs.yml
      - source: templates/workflows/changelogger.yml
        dest: .github/workflows/changelogger.yml
      - source: templates/workflows/release-update-wp-version.yml
        dest: .github/workflows/release-update-wp-version.yml
      - source: templates/workflows/skip-flags-parser.yml
        dest: .github/workflows/skip-flags-parser.yml
      - source: templates/workflows/main-release.yml
        dest: .github/workflows/main-release.yml
    repos: |
      the-events-calendar/events-pro@test/new-actions

  # Promoter (commented out for testing)
  # - files:
  #     - source: templates/pull_request_template.md
  #       dest: .github/pull_request_template.md
  #     - source: templates/workflows/link-project.yml
  #       dest: .github/workflows/link-project.yml
  #   repos: |
  #     the-events-calendar/promoter@server/production
