name: "Changelog: Add Entry"

on:
  workflow_dispatch:
    inputs:
      significance:
        description: "Significance of the change (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      type:
        description: "Type of change"
        required: true
        type: choice
        options:
          - version
          - feat
          - tweak
          - fix
          - performance
          - security
          - accessibility
          - compatibility
          - deprecated
          - language
      entry:
        description: "Changelog entry text"
        required: true
        type: string
      filename:
        description: "Custom filename (optional, will use branch name if not provided)"
        required: false
        type: string
      commit_type:
        description: "How to commit the changes"
        required: true
        type: choice
        default: direct_commit
        options:
          - pull_request
          - direct_commit

jobs:
  add-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}

      - name: Add changelog entry
        uses: stellarwp/changelogger@main
        with:
          command: add
          significance: ${{ github.event.inputs.significance }}
          type: ${{ github.event.inputs.type }}
          entry: ${{ github.event.inputs.entry }}
          filename: ${{ github.event.inputs.filename }}

      - name: Create Pull Request
        if: github.event.inputs.commit_type == 'pull_request'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          commit-message: "chore: add changelog entry"
          title: "chore: add changelog entry"
          body: |
            Adds a new changelog entry:

            - Significance: ${{ github.event.inputs.significance }}
            - Type: ${{ github.event.inputs.type }}
            - Entry: ${{ github.event.inputs.entry }}
            ${{ github.event.inputs.filename && format(' - Filename: {0}', github.event.inputs.filename) || '' }}
          branch: changelog/add-${{ github.sha }}
          base: ${{ github.ref_name }}
          delete-branch: true

      - name: Direct Commit
        if: github.event.inputs.commit_type == 'direct_commit'
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: add changelog entry"
          author_name: "GitHub Action"
          author_email: "action@github.com"
          default_author: github_actions
