name: "Release: Merge Forward"

on:
  workflow_dispatch:
    inputs:
      forward-branch:
        description: 'Name of the branch to merge into (e.g. release/T25.adamwarlock, master)'
        default: release/T25.name
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Print input vars to summary
        run: |
          echo "### Debugging Inputs" >> $GITHUB_STEP_SUMMARY
          echo "- forward-branch: \`${{ github.event.inputs['forward-branch'] }}\`" >> $GITHUB_STEP_SUMMARY

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set Variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Set up Git configuration
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Create and push release branch
        id: create-branch
        run: |
          forwardBranch="${{ github.event.inputs.forward-branch }}"
          if git show-ref --quiet "refs/heads/$forwardBranch"; then
            echo "skip=0" >> $GITHUB_OUTPUT
          else
            echo "## Pull Request"  >> $GITHUB_STEP_SUMMARY
            echo "Branch $forwardBranch does not exists, we dont need the create a PR." >> $GITHUB_STEP_SUMMARY
            git checkout -b "$forwardBranch"
            git push origin "$forwardBranch" || (git fetch origin "$forwardBranch" && git reset --hard "origin/$forwardBranch")
            echo "skip=1" >> $GITHUB_OUTPUT            
          fi

      - name: Create the merge Branch
        id: merge-branch
        if: ${{ steps.create-branch.outputs.skip == 0 }}
        run: |
          changeBranch="task/merge-forward-${{ github.ref_name }}-to-${{ github.event.inputs.forward-branch }}" 
          git checkout ${{ github.ref_name }}
          git checkout -b "$changeBranch"
          git push origin "$changeBranch"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: ${{ steps.create-branch.outputs.skip == 0 }}
        id: cpr
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          base: "${{ github.event.inputs.github.ref_name }}"
          branch: "task/merge-forward-${{ github.ref_name }}-to-${{ github.event.inputs.forward-branch }}" 
          title: "[BOT] Merge forward from '${{ github.ref_name }}' to '${{ github.event.inputs.forward-branch }}'"
          body: |
            This is an automated PR created by ${{ github.actor }}.
            It was generated by [this GitHub Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          labels: "automation"
          commit-message: |
            This is an automated PR created by ${{ github.actor }}.
            Generated by: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "## Pull Request"  >> $GITHUB_STEP_SUMMARY
          echo "* Number - ${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "* URL - [${{ steps.cpr.outputs.pull-request-url }}](${{ steps.cpr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
