name: 🔁 Sync Translations

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    secrets:
      TRANSLATIONS_DEPLOY_HOST:
        required: true
      TRANSLATIONS_DEPLOY_USER:
        required: true
      TRANSLATIONS_DEPLOY_SSH_KEY:
        required: true
      TRANSLATIONS_DEPLOY_POT_LOCATION:
        required: true

jobs:
  sync-translations:
    name: 🔁 Sync Translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          
      - name: Fetch Plugin Slug from .puprc
        id: puprc
        run: |
          plugin_slug=$(jq -r '.i18n[0].slug' .puprc)
          echo "plugin_slug=$plugin_slug" >> $GITHUB_ENV
          echo "plugin_slug=$plugin_slug" >> $GITHUB_OUTPUT
          echo "## Plugin Slug: \`$plugin_slug\`" >> $GITHUB_STEP_SUMMARY

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        if: ${{ inputs.install_composer_packages }}
        with:
          php_version: 7.4
          dev: no

      - uses: the-events-calendar/actions/.github/actions/generate-pot@main
        with:
          plugin_path: ${{ github.workspace }}
          pot_path: ${{github.workspace}}/languages/${{ steps.puprc.outputs.plugin_slug }}.pot

      - uses: the-events-calendar/actions/.github/actions/push-translations@main
        with:
          plugin_slug: ${{ steps.puprc.outputs.plugin_slug }}
        env:
          TRANSLATIONS_DEPLOY_HOST: ${{ secrets.TRANSLATIONS_DEPLOY_HOST }}
          TRANSLATIONS_DEPLOY_USER: ${{ secrets.TRANSLATIONS_DEPLOY_USER }}
          TRANSLATIONS_DEPLOY_SSH_KEY: ${{ secrets.TRANSLATIONS_DEPLOY_SSH_KEY }}
          TRANSLATIONS_DEPLOY_POT_LOCATION: ${{ secrets.TRANSLATIONS_DEPLOY_POT_LOCATION }}
