name: Merge Forward
description: 'Creates a pull request to merge changes from one branch to another for release management'

inputs:
  forward-branch:
    description: 'Name of the branch to merge into (e.g. release/T25.adamwarlock, master)'
    required: true
  gh-bot-token:
    description: 'GitHub bot token for authentication'
    required: false
    default: ${{ github.token }}

outputs:
  pull-request-url:
    description: 'URL of the created pull request'
    value: ${{ steps.create-pr.outputs.pr_url }}
  pull-request-created:
    description: 'Whether a pull request was created'
    value: ${{ steps.create-pr.outputs.created }}
  skip-reason:
    description: 'Reason why PR creation was skipped (if applicable)'
    value: ${{ steps.check-branch.outputs.skip_reason }}

runs:
  using: composite
  steps:
    - name: Setup environment
      uses: the-events-calendar/actions/.github/actions/base-setup@test/new-actions
      with:
        setup-php: 'false'
        setup-node: 'false'
        fetch-depth: '0'

    - name: Setup Git configuration
      uses: the-events-calendar/actions/.github/actions/setup-git@test/new-actions

    - name: Check if forward branch exists
      id: check-branch
      shell: bash
      run: |
        echo "## Branch Analysis" >> $GITHUB_STEP_SUMMARY
        echo "- **Forward Branch**: \`${{ inputs.forward-branch }}\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Current Branch**: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY

        if git ls-remote --exit-code --heads origin "${{ inputs.forward-branch }}"; then
          echo "✅ Forward branch exists, proceeding with merge" >> $GITHUB_STEP_SUMMARY
          echo "should_skip=false" >> $GITHUB_OUTPUT
          echo "skip_reason=" >> $GITHUB_OUTPUT
          git checkout "${{ inputs.forward-branch }}"
        else
          echo "⚠️ Forward branch does not exist, creating it" >> $GITHUB_STEP_SUMMARY
          echo "should_skip=true" >> $GITHUB_OUTPUT
          echo "skip_reason=Forward branch ${{ inputs.forward-branch }} does not exist" >> $GITHUB_OUTPUT

          # Create the branch so subsequent workflows can use it
          git checkout "${{ github.ref_name }}"
          git checkout -b "${{ inputs.forward-branch }}"
          git push origin "${{ inputs.forward-branch }}"
        fi

    - name: Create merge forward branch and merge
      if: steps.check-branch.outputs.should_skip == 'false'
      id: create-merge
      shell: bash
      run: |
        HEAD_BRANCH="task/merge-forward-${{ github.ref_name }}-to-${{ inputs.forward-branch }}"

        echo "## Creating Merge Branch" >> $GITHUB_STEP_SUMMARY
        echo "- **Head Branch**: \`$HEAD_BRANCH\`" >> $GITHUB_STEP_SUMMARY

        git checkout "${{ inputs.forward-branch }}"
        git checkout -b "$HEAD_BRANCH"

        # Attempt the merge
        if git merge --no-ff "${{ github.ref_name }}"; then
          echo "✅ Merge completed successfully" >> $GITHUB_STEP_SUMMARY
          git push origin "$HEAD_BRANCH"
          echo "merge_success=true" >> $GITHUB_OUTPUT
          echo "head_branch=$HEAD_BRANCH" >> $GITHUB_OUTPUT
        else
          echo "❌ Merge conflicts detected" >> $GITHUB_STEP_SUMMARY
          echo "merge_success=false" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Create Pull Request
      if: steps.check-branch.outputs.should_skip == 'false' && steps.create-merge.outputs.merge_success == 'true'
      id: create-pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh-bot-token }}
      run: |
        HEAD_BRANCH="${{ steps.create-merge.outputs.head_branch }}"

        echo "## Creating Pull Request" >> $GITHUB_STEP_SUMMARY

        # Create the PR using GitHub CLI
        PR_URL=$(gh pr create \
          --base "${{ inputs.forward-branch }}" \
          --head "$HEAD_BRANCH" \
          --title "[BOT] Merge forward from '${{ github.ref_name }}' to '${{ inputs.forward-branch }}'" \
          --body "This is an automated PR created by ${{ github.actor }}.

**Merge Details:**
- **Source**: \`${{ github.ref_name }}\`
- **Target**: \`${{ inputs.forward-branch }}\`
- **Generated by**: [GitHub Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

**Skip Flags**: [skip-changelog] [skip-lint] [skip-phpcs]

---
*This PR was automatically generated by the merge-forward action.*" \
          --assignee "${{ github.actor }}" \
          --label "automation,merge-forward")

        echo "✅ Pull request created successfully" >> $GITHUB_STEP_SUMMARY
        echo "- **URL**: [$PR_URL]($PR_URL)" >> $GITHUB_STEP_SUMMARY

        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        echo "created=true" >> $GITHUB_OUTPUT

    - name: Handle skipped PR creation
      if: steps.check-branch.outputs.should_skip == 'true'
      shell: bash
      run: |
        echo "## Pull Request Skipped" >> $GITHUB_STEP_SUMMARY
        echo "ℹ️ ${{ steps.check-branch.outputs.skip_reason }}" >> $GITHUB_STEP_SUMMARY
        echo "created=false" >> $GITHUB_OUTPUT
